services:
  postgres:
    image: postgres:16.3-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=swift_jobs
      - POSTGRES_USER=swift_jobs
      - POSTGRES_DB=swift_jobs
